# This is a basic workflow that is manually triggered

name: Post to social media

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Message to post'
        # Default value if no value is explicitly provided
        default: 'This is the new message to post on'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
    - name: get date
      run: export date=2022-12-03
      # run: export date=$(date +%Y-%m-%d)
    - name: list local _posts
      run: export files=$(ls _posts/${date}-*.md)
    - name: echo local _posts files
      run: echo "$files"
